version: '3'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
       - /var/www/mysql/data:/var/lib/mysql
       - /mnt/c/Users/Phuc Nguyen/Desktop/VMShare:/var/docker_share     
       - ./my.cnf:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
    container_name: mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on: 
      - db
    environment:
      PMA_HOST: db
#      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: root
    restart: always
    ports:
      - 8088:80
    volumes:
      - /sessions

